version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"  # Accès à Portainer via le port 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permet à Portainer de gérer Docker
      - portainer_data:/data  # Stocke les données persistantes de Portainer
    restart: always  # Redémarre automatiquement si le conteneur plante

volumes:
  portainer_data:  # Crée un volume persistant pour Portainer
